services:
  # Backend API Service
  - type: web
    name: nrg-datasense-backend
    env: python
    plan: starter
    buildCommand: |
      cd backend
      pip install -r requirements.txt
    startCommand: |
      cd backend
      python3 run.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: FLASK_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: nrg-datasense-db
          property: connectionString
      - key: NRG_CLIENT_ID
        sync: false
      - key: NRG_CLIENT_SECRET
        sync: false

  # Frontend Static Site
  - type: web
    name: nrg-datasense-frontend
    env: static
    plan: starter
    buildCommand: |
      npm install
      npm run build
    staticPublishPath: ./build
    envVars:
      - key: REACT_APP_API_URL
        value: https://nrg-datasense-backend.onrender.com
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

databases:
  - name: nrg-datasense-db
    databaseName: nrgdatasense
    user: nrgdatasense
    plan: starter 