services:
  # Unified FastAPI Backend with Email Monitoring
  - type: web
    name: nrg-datasense-backend
    env: python
    plan: free
    buildCommand: |
      cd backend
      chmod +x build.sh
      ./build.sh
    startCommand: |
      cd backend
      python run.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: PORT
        value: 5000
      - key: MONITOR_INTERVAL
        value: 300
      - key: MAX_FILES_PER_BATCH
        value: 10 