services:
  # FastAPI Backend Service
  - type: web
    name: nrg-datasense-backend
    env: python
    plan: free
    buildCommand: |
      cd backend
      pip install -r requirements.txt
    startCommand: |
      cd backend
      python run.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: PORT
        value: 5000

  # React Frontend Service
  - type: web
    name: nrg-datasense-frontend
    env: static
    plan: free
    buildCommand: |
      npm install
      npm run build
    staticPublishPath: ./build
    envVars:
      - key: REACT_APP_API_URL
        value: https://nrg-datasense-backend.onrender.com
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

databases:
  - name: nrg-datasense-db
    databaseName: nrgdatasense
    user: nrgdatasense
    plan: starter 