services:
  # Unified FastAPI Backend with Email Monitoring
  - type: web
    name: nrg-datasense-backend
    env: python
    plan: free
    buildCommand: |
      cd backend
      pip install -r requirements.txt
    startCommand: |
      cd backend
      python run.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: PORT
        value: 5000
      - key: MONITOR_INTERVAL
        value: 300
      - key: MAX_FILES_PER_BATCH
        value: 10

  # React Frontend (Static Site)
  - type: static
    name: nrg-datasense-frontend
    env: static
    plan: free
    buildCommand: |
      npm install
      npm run build
    staticPublishPath: ./build
    envVars:
      - key: REACT_APP_API_URL
        value: https://nrg-datasense-backend.onrender.com 