#!/bin/bash

echo ""
echo "========================================"
echo "   DataSense - Mac Version"
echo "========================================"
echo ""
echo "⚠️  IMPORTANT: DataSense requires Windows for RLD conversion"
echo ""
echo "DataSense uses nrgpy for RLD file conversion, which requires"
echo "the official NRG Systems software that only runs on Windows."
echo ""
echo "Options for Mac users:"
echo ""
echo "1. 🖥️  Use Windows VM with DataSense"
echo "   - Install Parallels Desktop or VMware Fusion"
echo "   - Create Windows 10/11 VM"
echo "   - Install NRG Systems software in VM"
echo "   - Run DataSense in Windows VM"
echo ""
echo "2. 🌐 Use Windows machine for conversion"
echo "   - Install DataSense on Windows machine"
echo "   - Use for RLD file conversion"
echo "   - Transfer converted files to Mac"
echo ""
echo "3. ☁️  Use cloud-based Windows service"
echo "   - Deploy Windows VM in cloud (AWS/Azure)"
echo "   - Use for remote RLD conversion"
echo "   - API-based communication"
echo ""
echo "For detailed VM setup instructions, see:"
echo "  WINDOWS_VM_SETUP.md"
echo ""
echo "For Windows deployment, please use:"
echo "  start-datasense.bat"
echo ""
read -p "Press Enter to exit..."
