#!/bin/bash

echo ""
echo "========================================"
echo "   DataSense - Linux Host Setup"
echo "========================================"
echo ""
echo "🖥️  DataSense runs inside a Windows VM"
echo ""
echo "DataSense is designed to run inside a Windows VM alongside"
echo "the official NRG Systems software for complete functionality."
echo ""
echo "Setup Instructions:"
echo ""
echo "1. 🖥️  Create Windows VM"
echo "   - Install VirtualBox or VMware"
echo "   - Create Windows 10/11 VM (4GB+ RAM, 50GB+ storage)"
echo "   - Install Windows 10/11 in VM"
echo ""
echo "2. 📦 Install Software in VM"
echo "   - Install NRG Systems software in Windows VM"
echo "   - Download DataSense inside Windows VM"
echo "   - Run start-datasense.bat inside Windows VM"
echo ""
echo "3. 🚀 Use DataSense"
echo "   - Access Windows VM from Linux host"
echo "   - Use DataSense like any Windows application"
echo "   - Full nrgpy functionality with NRG Systems software"
echo ""
echo "For detailed VM setup instructions, see:"
echo "  WINDOWS_VM_SETUP.md"
echo ""
echo "Once VM is set up, use inside Windows VM:"
echo "  start-datasense.bat"
echo ""
read -p "Press Enter to exit..."
